/**
 * DOCX Template Detection - Thin Wrapper
 *
 * This module re-exports detection functions from the centralized
 * templates/detection.ts module for backward compatibility.
 *
 * NEW CODE SHOULD IMPORT DIRECTLY FROM:
 * - ../templates/detection.ts (for detection functions)
 * - ../templates/registry.ts (for template definitions)
 */

import { shouldSendAsDocx as centralizedShouldSendAsDocx } from "../templates/detection.ts";
import { LogCategory, logger } from "../utils/logger.ts";

// Re-export all detection functions from centralized module
export {
  containsPlaceholders,
  type DocxTemplateType,
  detectDocxTemplateType,
  isClarificationQuestion,
  isCompletedMarketingAgreement,
  isCompletedReservationAgreement,
  isCompletedViewingForm,
  isConfirmationMessage,
  shouldSendAsDocx,
  wasDocxTemplateRequested,
} from "../templates/detection.ts";

// Re-export registry functions
export {
  DOCX_TEMPLATE_TITLES,
  extractTemplateTitle,
  isDocxTemplateTitle,
} from "../templates/registry.ts";

/**
 * Minimum content requirements for a valid DOCX document
 */
const MIN_DOCUMENT_LENGTH = 100;
const MIN_DOCUMENT_LINES = 3;

/**
 * Placeholder messages that should NEVER be sent as documents
 */
const PLACEHOLDER_PATTERNS = [
  /^document generated by sophia\.?$/i,
  /^document generated\.?$/i,
  /^here is your document\.?$/i,
  /^your document has been generated\.?$/i,
  /^document created\.?$/i,
  /^generating document\.?$/i,
];

/**
 * Validates if the AI response contains actual document content
 * Rejects placeholder messages and too-short responses
 */
export function hasValidDocumentContent(response: string): boolean {
  const trimmed = response.trim();

  // Reject very short responses
  if (trimmed.length < MIN_DOCUMENT_LENGTH) {
    logger.debug(
      `[DOCX Detector] Response too short: ${trimmed.length} chars (min: ${MIN_DOCUMENT_LENGTH})`,
      { category: LogCategory.GENERAL }
    );
    return false;
  }

  // Reject placeholder messages
  for (const pattern of PLACEHOLDER_PATTERNS) {
    if (pattern.test(trimmed)) {
      logger.debug("[DOCX Detector] Response matches placeholder pattern", {
        category: LogCategory.GENERAL,
      });
      return false;
    }
  }

  // Check line count
  const lines = trimmed.split("\n").filter((line) => line.trim().length > 0);
  if (lines.length < MIN_DOCUMENT_LINES) {
    logger.debug(
      `[DOCX Detector] Too few lines: ${lines.length} (min: ${MIN_DOCUMENT_LINES})`,
      { category: LogCategory.GENERAL }
    );
    return false;
  }

  return true;
}

/**
 * Main detection function - determines if response should be DOCX
 * This is a wrapper around shouldSendAsDocx for backward compatibility
 *
 * @param aiResponse - The AI's response text
 * @param _conversationHistory - Optional conversation history for context (unused but kept for API compatibility)
 * @returns boolean - true if should send as DOCX, false for TEXT
 */
export function isDocxTemplate(
  aiResponse: string,
  _conversationHistory?: Array<{ role: string; parts: Array<{ text: string }> }>
): boolean {
  // Step 1: Check if response has Subject: line -> always TEXT (it's an email)
  if (aiResponse.includes("Subject:")) {
    logger.debug("[DOCX Detector] Has Subject: line -> TEXT message", {
      category: LogCategory.GENERAL,
    });
    return false;
  }

  // Step 2: Validate content is substantial enough for a document
  if (!hasValidDocumentContent(aiResponse)) {
    logger.debug("[DOCX Detector] Content validation failed -> TEXT message", {
      category: LogCategory.GENERAL,
    });
    return false;
  }

  // Step 3: Use the centralized detection
  return centralizedShouldSendAsDocx(aiResponse);
}
