/**
 * DOCX Template Detection
 *
 * Determines if an AI response should be sent as a DOCX file attachment
 * or as a text message. Only 4 specific templates are DOCX:
 *
 * - Standard Viewing Form (Template 09)
 * - Advanced Viewing Form (Template 10)
 * - Property Reservation Agreement (Template 11)
 * - Non-Exclusive Marketing Agreement (Template 15)
 *
 * All other templates are sent as TEXT messages.
 */

import { shouldSendAsDocx, extractTemplateTitle } from "../prompts/templates/registry.ts";

/**
 * Minimum content requirements for a valid DOCX document
 */
const MIN_DOCUMENT_LENGTH = 100;
const MIN_DOCUMENT_LINES = 3;

/**
 * Placeholder messages that should NEVER be sent as documents
 */
const PLACEHOLDER_PATTERNS = [
  /^document generated by sophia\.?$/i,
  /^document generated\.?$/i,
  /^here is your document\.?$/i,
  /^your document has been generated\.?$/i,
  /^document created\.?$/i,
  /^generating document\.?$/i,
];

/**
 * Validates if the AI response contains actual document content
 * Rejects placeholder messages and too-short responses
 */
export function hasValidDocumentContent(response: string): boolean {
  const trimmed = response.trim();
  
  // Reject very short responses
  if (trimmed.length < MIN_DOCUMENT_LENGTH) {
    console.log(`[DOCX Detector] Response too short: ${trimmed.length} chars (min: ${MIN_DOCUMENT_LENGTH})`);
    return false;
  }
  
  // Reject placeholder messages
  for (const pattern of PLACEHOLDER_PATTERNS) {
    if (pattern.test(trimmed)) {
      console.log(`[DOCX Detector] Response matches placeholder pattern`);
      return false;
    }
  }
  
  // Check line count
  const lines = trimmed.split('\n').filter(line => line.trim().length > 0);
  if (lines.length < MIN_DOCUMENT_LINES) {
    console.log(`[DOCX Detector] Too few lines: ${lines.length} (min: ${MIN_DOCUMENT_LINES})`);
    return false;
  }
  
  return true;
}

/**
 * Main detection function - determines if response should be DOCX
 * 
 * @param aiResponse - The AI's response text
 * @param conversationHistory - Optional conversation history for context
 * @returns boolean - true if should send as DOCX, false for TEXT
 */
export function isDocxTemplate(
  aiResponse: string,
  conversationHistory?: Array<{role: string, parts: Array<{text: string}>}>
): boolean {
  // Step 1: Check if response has Subject: line -> always TEXT (it's an email)
  if (aiResponse.includes("Subject:")) {
    console.log("[DOCX Detector] Has Subject: line -> TEXT message");
    return false;
  }
  
  // Step 2: Validate content is substantial enough for a document
  if (!hasValidDocumentContent(aiResponse)) {
    console.log("[DOCX Detector] Content validation failed -> TEXT message");
    return false;
  }
  
  // Step 3: Use the registry to determine if this is a DOCX template
  const isDocx = shouldSendAsDocx(aiResponse);
  
  const title = extractTemplateTitle(aiResponse);
  console.log(`[DOCX Detector] Title: "${title}", Is DOCX: ${isDocx}`);
  
  return isDocx;
}

/**
 * Check if a DOCX template was requested based on conversation history
 * Useful for detecting when AI failed to generate proper document content
 */
export function wasDocxTemplateRequested(
  conversationHistory?: Array<{role: string, parts: Array<{text: string}>}>
): boolean {
  if (!conversationHistory || conversationHistory.length === 0) {
    return false;
  }
  
  const allMessages = conversationHistory
    .map(msg => msg.parts.map(p => p.text).join(" "))
    .join(" ")
    .toLowerCase();
  
  // Check for explicit DOCX template requests
  const docxKeywords = [
    "viewing form",
    "standard viewing",
    "advanced viewing",
    "reservation agreement",
    "property reservation",
    "non-exclusive",
    "non exclusive",
    "marketing agreement",
    "signature document",
    "template 09",
    "template 10",
    "template 11",
    "template 15",
  ];
  
  return docxKeywords.some(keyword => allMessages.includes(keyword));
}

/**
 * Detect specific DOCX template type from response content
 * Returns the template identifier for specialized generation
 */
export type DocxTemplateType =
  | "viewing-form-single"
  | "viewing-form-multiple"
  | "viewing-form-advanced"
  | "reservation-agreement"
  | "marketing-non-exclusive"
  | "unknown";

export function detectDocxTemplateType(response: string): DocxTemplateType {
  const lower = response.toLowerCase();
  const first500 = lower.substring(0, 500);
  
  // Viewing Forms
  if (first500.includes("viewing form") || first500.includes("herein, i")) {
    // Check for advanced (has legal paragraph)
    if (lower.includes("exclusive representative") || 
        lower.includes("monetary compensation") ||
        lower.includes("commission fee")) {
      // Check for multiple people
      if (lower.includes("and i ") && (lower.match(/with id/gi) || []).length > 1) {
        return "viewing-form-multiple"; // Advanced with multiple people would need separate template
      }
      return "viewing-form-advanced";
    }
    
    // Check for multiple people (standard)
    if (lower.includes("and i ") && (lower.match(/with id/gi) || []).length > 1) {
      return "viewing-form-multiple";
    }
    
    return "viewing-form-single";
  }
  
  // Reservation Agreement
  if (first500.includes("reservation agreement") || first500.includes("property reservation agreement") || first500.includes("property reservation")) {
    return "reservation-agreement";
  }

  // Marketing Agreement (Non-Exclusive)
  if (first500.includes("marketing agreement") ||
      (first500.includes("non-exclusive") && lower.includes("agent may advertise"))) {
    return "marketing-non-exclusive";
  }

  return "unknown";
}

