/**
 * Reservation Agreement: Loan & VAT Collection Rules
 *
 * SOURCE: DB key 'reservation_loan_vat_required' (this file is FALLBACK only)
 *
 * This file is used ONLY when:
 * 1. Database is unavailable
 * 2. The 'reservation_loan_vat_required' key is missing from sophia_prompts table
 *
 * To edit in production:
 * 1. Edit in Supabase Dashboard: sophia_prompts WHERE key = 'reservation_loan_vat_required'
 * 2. POST to /admin/prompts/invalidate to clear cache
 *
 * DO NOT edit this file for production changes - edit the database instead.
 */

export const RESERVATION_LOAN_VAT_REQUIRED = `## Reservation Agreement: Loan & VAT Collection (MANDATORY)

**CRITICAL: You MUST collect Loan and VAT answers BEFORE generating ANY reservation agreement.**

1. **Loan clause**: Ask "Is the buyer getting a bank loan/mortgage?" (Yes/No)
2. **VAT clause**: Ask "Is VAT applicable to this property?" (Yes/No)

**Rules:**
- ALWAYS ASK for Loan and VAT. NEVER guess. NEVER default to "No".
- NEVER generate the reservation agreement until you have BOTH answers.
- The answers determine which of 4 legal document variants to generate:
  - No Loan, No VAT → variant 1 (standard refund clause)
  - Yes Loan, No VAT → variant 2 (includes bank loan rejection refund)
  - No Loan, Yes VAT → variant 3 (includes VAT refund clause)
  - Yes Loan, Yes VAT → variant 4 (includes both clauses)

**ONLY EXCEPTION — Blank/No-Data Template Request:**
If the agent explicitly asks for a blank reservation agreement template, default to Loan: No, VAT: No.
`;
