/**
 * SOPHIA Document Templates - Barrel Export
 *
 * SOURCE: DB key 'templates' (this file is FALLBACK only)
 *
 * This file is used ONLY when:
 * 1. Database is unavailable
 * 2. The 'templates' key is missing from sophia_prompts table
 *
 * To edit templates in production:
 * 1. Edit in Supabase Dashboard: sophia_prompts WHERE key = 'templates'
 * 2. POST to /sophia-bot/admin/prompts/invalidate to clear cache
 *
 * DO NOT edit this file for production changes - edit the database instead.
 *
 * All 43 templates for Cyprus real estate communications organized into:
 * - header.ts: Documentation, rules, quick reference table
 * - registrations.ts: 8 Registration templates (Seller, Bank, Developer)
 * - viewing-forms.ts: Viewing forms + Reservation Agreement (DOCX)
 * - marketing.ts: Marketing agreements (2 types)
 * - client-comms.ts: 27+ Client communication templates
 * - appendix.ts: CREA wording, troubleshooting, checklist
 *
 * Output Types:
 * - TEXT: Sent as WhatsApp messages
 * - DOCX: Sent as file attachments (Viewing Forms, Reservation, Non-Exclusive Marketing)
 *
 * ==== CENTRALIZED SOURCES OF TRUTH ====
 * The following rules embedded in this prompt have CODE equivalents in:
 *
 * BANK DETECTION: ../rules/bank-detection.ts
 *   - detectBankFromUrl(), BANK_URL_PATTERNS, BANK_DETECTION_PROMPT
 *
 * PHONE MASKING: ../rules/phone-masking.ts
 *   - maskPhoneNumber(), PHONE_MASKING_PROMPT
 *
 * EMAIL FORMAT: ../rules/email-format.ts
 *   - parseEmailParts(), EMAIL_FORMAT_PROMPT
 *
 * TEMPLATE REGISTRY: ../../templates/registry.ts
 *   - TEMPLATE_REGISTRY, DOCX_TEMPLATE_TITLES, getTemplateOutputType()
 *
 * DETECTION LOGIC: ../../templates/detection.ts
 *   - shouldSendAsDocx(), isClarificationQuestion(), isCompletedReservationAgreement()
 *
 * When updating rules in THIS file, also update the corresponding module.
 * ===========================================
 */

import { HEADER } from "./header.ts";
import { REGISTRATIONS } from "./registrations.ts";
import { VIEWING_FORMS } from "./viewing-forms.ts";
import { MARKETING } from "./marketing.ts";
import { CLIENT_COMMS } from "./client-comms.ts";
import { APPENDIX } from "./appendix.ts";

export const TEMPLATES = `${HEADER}
${REGISTRATIONS}
${VIEWING_FORMS}
${MARKETING}
${CLIENT_COMMS}
${APPENDIX}`;
